name: linkcheck
version: 3.0.0 # Don't forget to update in lib/linkcheck.dart, too.

description: >-
  A very fast link-checker. Crawls sites and checks integrity of links
  both in HTML and in CSS.

homepage: https://github.com/filiph/linkcheck

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.0.0
  console: ^4.1.0
  csslib: ^0.17.0
  glob: ^2.0.1
  html: ^0.15.0
  path: ^1.8.0
  source_span: ^1.8.0
  stream_channel: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  dhttpd: ^4.0.0
  test: ^1.22.0
  cli_pkg: ^2.1.6
  grinder: ^0.9.2

executables:
  linkcheck: linkcheck
