name: linkcheck
version: 0.2.6  # Don't forget to update in bin/linkcheck.dart
description: A very fast link-checker.
homepage: https://github.com/filiph/linkcheck
author: "Filip Hracek <filip.hracek@gmail.com>"
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  args: ^0.13.4+2
  console: ^2.2.3
  csslib: ^0.13.2
  glob: ^1.1.3
  html: ^0.13.0
  path: ^1.3.9
  stream_channel: ^1.5.0
dev_dependencies:
  test:
executables:
  linkcheck: linkcheck