name: linkcheck
version: 3.1.0 # Don't forget to update in lib/linkcheck.dart, too.

description: >-
  A very fast link-checker. Crawls sites and checks integrity of links
  both in HTML and in CSS.

repository: https://github.com/filiph/linkcheck

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  console: ^4.1.0
  csslib: ^1.0.0
  glob: ^2.1.2
  html: ^0.15.4
  meta: ^1.9.1
  path: ^1.8.3
  source_span: ^1.10.0
  stream_channel: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  dhttpd: ^4.0.0
  test: ^1.24.4
  cli_pkg: ^2.5.0
  grinder: ^0.9.4

executables:
  linkcheck: linkcheck
